apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ui
  template:
    metadata:
      labels:
        app: demo-ui
    spec:
      containers:
        - name: demo-ui
          image: demo-ui:latest
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: demo-ui
spec:
  selector:
    app: demo-ui
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
