apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels: 
    app: demo
    tier: database 
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: demo
      tier: database
  template:
    metadata:
      labels:
        app: demo
        tier: database
    spec:
      containers:
      - name: postgres
        image: pradhikshaks/postgres-init
        env:
        - name: POSTGRES_USER
          value: vibav
        - name: POSTGRES_PASSWORD
          value: vibav
        - name: POSTGRES_DB
          value: db
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
          
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: demo
    tier: database
spec:
  type: ClusterIP
  selector:
    app: demo
    tier: database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  
